name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Rust
        run: rustup update stable && rustup default stable

      - name: Format check
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy --locked --all-targets -- -D warnings -W clippy::pedantic -W clippy::nursery -W clippy::cargo -W clippy::unreachable -W clippy::dbg_macro -W clippy::todo -W clippy::unimplemented -W clippy::exit -A clippy::too_many_lines

      - name: Build
        run: cargo build --locked

      - name: Run tests
        run: cargo test --locked
