name: Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  release:
    name: Release native binaries
    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            arch: amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin_ext: ""
          - os: linux
            arch: arm64
            runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            bin_ext: ""
          - os: macos
            arch: amd64
            runner: macos-15-intel
            target: x86_64-apple-darwin
            bin_ext: ""
          - os: macos
            arch: arm64
            runner: macos-latest
            target: aarch64-apple-darwin
            bin_ext: ""
          - os: windows
            arch: amd64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
            bin_ext: .exe
          - os: windows
            arch: arm64
            runner: windows-11-arm
            target: aarch64-pc-windows-msvc
            bin_ext: .exe

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Rust
        run: rustup update stable && rustup default stable

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build release
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Pack
        shell: bash
        run: |
          release_name="oppo-multiplexer-${{ matrix.os }}-${{ matrix.arch }}"
          binary="target/${{ matrix.target }}/release/oppo-multiplexer${{ matrix.bin_ext }}"
          if [ "${{ matrix.os }}" = "windows" ]; then
            7z a -tzip "${release_name}.zip" "$binary"
          else
            tar -czvf "${release_name}.tar.gz" -C "target/${{ matrix.target }}/release" "oppo-multiplexer"
          fi

      - name: Publish
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          files: |
            oppo-multiplexer*.zip
            oppo-multiplexer*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest build provenance
        uses: actions/attest@f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6 # v4.2.0
        with:
          subject-path: |
            oppo-multiplexer*.tar.gz
            oppo-multiplexer*.zip
